### ISSUE TITLE
suddenly Login failure

### ISSUE THREAD

**Issue by MadPatrick** [MadPatrick/somfy#36]
Not sure what happened, but i tried to test the web version which worked for 1 movement of the screen and then i could not operated the screens any more.
Login failure

Setting back to local and now i can use the screens anymore

```
2022-12-01 20:00:37.754 Somfy: Parameter: 'Key':'tahomaIO'
2022-12-01 20:00:37.754 Somfy: Parameter: 'Mode1':'False'
2022-12-01 20:00:37.754 Somfy: Parameter: 'Mode2':'20'
2022-12-01 20:00:37.754 Somfy: Parameter: 'Mode3':'xxxx-xxxx-xxxx'
2022-12-01 20:00:37.754 Somfy: Parameter: 'Mode4':'Local'
2022-12-01 20:00:37.754 Somfy: Parameter: 'Mode5':'/var/log/somfy/'
2022-12-01 20:00:37.754 Somfy: Parameter: 'Mode6':'Debug'
2022-12-01 20:00:37.754 Somfy: Parameter: 'DomoticzVersion':'2022.2'
2022-12-01 20:00:37.754 Somfy: Parameter: 'DomoticzHash':'0'
2022-12-01 20:00:37.754 Somfy: Parameter: 'DomoticzBuildTime':'1970-01-01 01:00:00'
2022-12-01 20:00:37.754 Somfy: Configuration count: 5
2022-12-01 20:00:37.754 Somfy: Configuration 'MajorVersion':'4'
2022-12-01 20:00:37.754 Somfy: Configuration 'MinorVersion':'1'
2022-12-01 20:00:37.754 Somfy: Configuration 'patchVersion':'7'
2022-12-01 20:00:37.754 Somfy: Configuration 'plugin version':'4.1.7'
2022-12-01 20:00:37.754 Somfy: Configuration 'token':'635407f4b6f0727cb13d'
2022-12-01 20:00:37.754 Somfy: Device count: 12
2022-12-01 20:00:37.754 Somfy: Device: internal://xxxx-xxxx-xxxx/pod/0 - DeviceID: 'internal://xxxx-xxxx-xxxx/pod/0', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/10464619 - DeviceID: 'io://xxxx-xxxx-xxxx/10464619', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/1118656 - DeviceID: 'io://xxxx-xxxx-xxxx/1118656', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/14852843 - DeviceID: 'io://xxxx-xxxx-xxxx/14852843', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/16752266 - DeviceID: 'io://xxxx-xxxx-xxxx/16752266', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/2192664 - DeviceID: 'io://xxxx-xxxx-xxxx/2192664', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/2331376 - DeviceID: 'io://xxxx-xxxx-xxxx/2331376', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/3280315 - DeviceID: 'io://xxxx-xxxx-xxxx/3280315', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/3424709 - DeviceID: 'io://xxxx-xxxx-xxxx/3424709', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/7005214 - DeviceID: 'io://xxxx-xxxx-xxxx/7005214', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/7959673 - DeviceID: 'io://xxxx-xxxx-xxxx/7959673', Units: 1
2022-12-01 20:00:37.754 Somfy: Device: io://xxxx-xxxx-xxxx/8024168 - DeviceID: 'io://xxxx-xxxx-xxxx/8024168', Units: 1
2022-12-01 20:00:37.754 Somfy: os.path.exists(Parameters['Mode5']) = True
2022-12-01 20:00:37.755 Somfy: Starting version: 4.1.7
2022-12-01 20:00:37.475 Status: Somfy: Started.
2022-12-01 20:00:37.475 Status: Somfy: Entering work loop.
2022-12-01 20:00:37.751 Status: Somfy: Initialized version 4.1.7, author 'MadPatrick'
2022-12-01 20:00:37.753 Status: Somfy: Starting Tahoma blind plugin, logging to file /var/log/somfy/somfy.log
2022-12-01 20:00:37.855 Error: Somfy: Failed to login: Bad credentials, please update credentials and restart plugin
2022-12-01 20:00:57.095 Error: Somfy: Call to function 'onHeartbeat' failed, exception details:
2022-12-01 20:00:57.096 Error: Somfy: Traceback (most recent call last):
2022-12-01 20:00:57.096 Error: Somfy: File "/var/domoticz/plugins/somfy/plugin.py", line 576, in onHeartbeat
2022-12-01 20:00:57.096 Error: Somfy: _plugin.onHeartbeat()
2022-12-01 20:00:57.096 Error: Somfy: File "/var/domoticz/plugins/somfy/plugin.py", line 295, in onHeartbeat
2022-12-01 20:00:57.096 Error: Somfy: event_list = self.tahoma.get_events()
2022-12-01 20:00:57.096 Error: Somfy: File "/var/domoticz/plugins/somfy/tahoma_local.py", line 212, in get_events
2022-12-01 20:00:57.096 Error: Somfy: raise exceptions.TahomaException("No token has been provided")
2022-12-01 20:00:57.096 Error: Somfy: exceptions.TahomaException: No token has been provided
2022-12-01 20:01:17.089 Error: Somfy: Call to function 'onHeartbeat' failed, exception details:
2022-12-01 20:01:17.089 Error: Somfy: Traceback (most recent call last):
2022-12-01 20:01:17.089 Error: Somfy: File "/var/domoticz/plugins/somfy/plugin.py", line 576, in onHeartbeat
2022-12-01 20:01:17.089 Error: Somfy: _plugin.onHeartbeat()
2022-12-01 20:01:17.089 Error: Somfy: File "/var/domoticz/plugins/somfy/plugin.py", line 295, in onHeartbeat
2022-12-01 20:01:17.089 Error: Somfy: event_list = self.tahoma.get_events()
2022-12-01 20:01:17.089 Error: Somfy: File "/var/domoticz/plugins/somfy/tahoma_local.py", line 212, in get_events
2022-12-01 20:01:17.089 Error: Somfy: raise exceptions.TahomaException("No token has been provided")
2022-12-01 20:01:17.089 Error: Somfy: exceptions.TahomaException: No token has been provided
2022-12-01 20:01:36.472 Status: Somfy: Stop directive received.
```

```
2022-12-01 19:50:28,662 - DEBUG    - plugin.py          - starting to log in with mode Local
2022-12-01 19:50:28,662 - DEBUG    - listener.py        - listener created
2022-12-01 19:50:28,662 - DEBUG    - tahoma_local.py    - SomfyBox initialised
2022-12-01 19:50:28,665 - DEBUG    - connectionpool.py  - Starting new HTTPS connection (1): ha101-1.overkiz.com:443
2022-12-01 19:50:28,756 - DEBUG    - connectionpool.py  - https://ha101-1.overkiz.com:443 "POST /enduser-mobile-web/enduserAPI/login HTTP/1.1" 401 None
2022-12-01 19:50:28,758 - DEBUG    - tahoma_local.py    - Login respone: status_code: '401' reponse body: '{'errorCode': 'AUTHENTICATION_ERROR', 'error': 'Bad credentials'}'
2022-12-01 19:50:28,758 - ERROR    - tahoma_local.py    - login failed: Bad credentials, please update credentials and restart plugin
```

Tried to reset the token, but no change

tried the test_tahoma.py script and with option 1 
`Failed to login: Bad credentials, please update credentials and restart plugin
login status: False
Press Enter to continue...`

What can be the issue ?

**Comment by MadPatrick** [comment]
Somfy site was out-of-service
Strange since i'm using local mode

**Comment by JanJaapKo** [comment]
@MadPatrick at first login when no token available we contact the webserver for the token. Shall we park this issue for now and see first how to solve the Connexxoon issues and then check if your tahoma box still works ok?

**Comment by MadPatrick** [comment]
Definately no priority for now.
Let first focus to get it working for the Connexoon.

I thought that the Connexoon was working fine with the old plugin, so it should have issue with the changes.

**Comment by JanJaapKo** [comment]
yes well I tried to keep the old one working (you and Ab helped also to test that) but apparently somethings did get different somehow.... It would be nice to get that back to work again.

**Comment by MadPatrick** [comment]
@JanJaapKo JanJaap 

I think we can close this one

**Comment by JanJaapKo** [comment]
Think so too
