### ISSUE TITLE
Some commands lead to 400 response

### ISSUE THREAD

**Issue by JanJaapKo** [MadPatrick/somfy#40]
**Describe the bug**
During some commands the response is 400

**To Reproduce**

**Expected behavior**
command executed and no error

**Domoticz info:**
 - Device: [e.g. rasberry pi]
 - OS: [e.g. bullseye]
 - Domoticz Version [e.g. 2022.2 or latest beta]

**Box info:**
 - Box type: Connexoon

**Additional context**

**Somfy.log**
make sure to paste here the logging from somfy.log file (or attach the file itself) while running the plugin in debug mode

**Domoticz logging**
[somfy2.log](https://github.com/MadPatrick/somfy/files/10359712/somfy2.log)

Domoticz logs :
```
2023-01-06 09:31:15.382 Error: Volets roulants: Call to function 'onCommand' failed, exception details:
2023-01-06 09:31:15.383 Error: Volets roulants: Traceback (most recent call last):
2023-01-06 09:31:15.383 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 582, in onCommand
2023-01-06 09:31:15.383 Error: Volets roulants: _plugin.onCommand(DeviceId, Unit, Command, Level, Color)
2023-01-06 09:31:15.383 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 267, in onCommand
2023-01-06 09:31:15.383 Error: Volets roulants: self.tahoma.send_command(self.command_data)
2023-01-06 09:31:15.383 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 226, in send_command
2023-01-06 09:31:15.383 Error: Volets roulants: self.handle_response(response, "send command")
2023-01-06 09:31:15.383 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 239, in handle_response
2023-01-06 09:31:15.383 Error: Volets roulants: raise exceptions.TahomaException("failed request during "+ action + ", check url or body: " + str(response.status_code))
2023-01-06 09:31:15.383 Error: Volets roulants: exceptions.TahomaException: failed request during send command, check url or body: 400 
```

**Comment by Abidos14** [comment]
On my side, it seem that the erro occurs when several commands are launched successively.

Domoticz logs
2023-01-06 14:16:54.281 Status: User: Admin (IP: 192.168.90.15) initiated a switch command (841/Cuisine/Set Level) 
2023-01-06 14:16:54.524 Error: Volets roulants: Call to function 'onCommand' failed, exception details: 
2023-01-06 14:16:54.525 Error: Volets roulants: Traceback (most recent call last): 
2023-01-06 14:16:54.525 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 582, in onCommand 
2023-01-06 14:16:54.525 Error: Volets roulants: _plugin.onCommand(DeviceId, Unit, Command, Level, Color) 
2023-01-06 14:16:54.525 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 268, in onCommand 
2023-01-06 14:16:54.525 Error: Volets roulants: event_list = self.tahoma.get_events() 
2023-01-06 14:16:54.525 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 132, in get_events 
2023-01-06 14:16:54.525 Error: Volets roulants: raise exceptions.TahomaException("No listenerId has been provided") 
2023-01-06 14:16:54.525 Error: Volets roulants: exceptions.TahomaException: No listenerId has been provided 
2023-01-06 14:16:57.044 Status: User: Admin (IP: 192.168.90.15) initiated a switch command (840/Salon 2/Set Level) 
2023-01-06 14:16:57.370 Error: Volets roulants: Call to function 'onCommand' failed, exception details: 
2023-01-06 14:16:57.371 Error: Volets roulants: Traceback (most recent call last): 
2023-01-06 14:16:57.371 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 582, in onCommand 
2023-01-06 14:16:57.371 Error: Volets roulants: _plugin.onCommand(DeviceId, Unit, Command, Level, Color) 
2023-01-06 14:16:57.371 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 268, in onCommand 
2023-01-06 14:16:57.371 Error: Volets roulants: event_list = self.tahoma.get_events() 
2023-01-06 14:16:57.371 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 132, in get_events 
2023-01-06 14:16:57.371 Error: Volets roulants: raise exceptions.TahomaException("No listenerId has been provided") 
2023-01-06 14:16:57.371 Error: Volets roulants: exceptions.TahomaException: No listenerId has been provided 
2023-01-06 14:17:13.018 Status: User: Admin (IP: 192.168.90.15) initiated a switch command (840/Salon 2/Open) 
2023-01-06 14:17:13.259 Error: Volets roulants: Call to function 'onCommand' failed, exception details: 
2023-01-06 14:17:13.259 Error: Volets roulants: Traceback (most recent call last): 
2023-01-06 14:17:13.259 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 582, in onCommand 
2023-01-06 14:17:13.259 Error: Volets roulants: _plugin.onCommand(DeviceId, Unit, Command, Level, Color) 
2023-01-06 14:17:13.259 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 267, in onCommand 
2023-01-06 14:17:13.259 Error: Volets roulants: self.tahoma.send_command(self.command_data) 
2023-01-06 14:17:13.259 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 226, in send_command 
2023-01-06 14:17:13.259 Error: Volets roulants: self.handle_response(response, "send command") 
2023-01-06 14:17:13.259 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 239, in handle_response 
2023-01-06 14:17:13.259 Error: Volets roulants: raise exceptions.TahomaException("failed request during "+ action + ", check url or body: " + str(response.status_code)) 
2023-01-06 14:17:13.259 Error: Volets roulants: exceptions.TahomaException: failed request during send command, check url or body: 400 
2023-01-06 14:17:14.008 Status: User: Admin (IP: 192.168.90.15) initiated a switch command (841/Cuisine/Open) 
2023-01-06 14:17:14.858 Error: Volets roulants: Call to function 'onCommand' failed, exception details: 
2023-01-06 14:17:14.859 Error: Volets roulants: Traceback (most recent call last): 
2023-01-06 14:17:14.859 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 582, in onCommand 
2023-01-06 14:17:14.859 Error: Volets roulants: _plugin.onCommand(DeviceId, Unit, Command, Level, Color) 
2023-01-06 14:17:14.859 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 267, in onCommand 
2023-01-06 14:17:14.859 Error: Volets roulants: self.tahoma.send_command(self.command_data) 
2023-01-06 14:17:14.859 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 226, in send_command 
2023-01-06 14:17:14.859 Error: Volets roulants: self.handle_response(response, "send command") 
2023-01-06 14:17:14.859 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 239, in handle_response 
2023-01-06 14:17:14.859 Error: Volets roulants: raise exceptions.TahomaException("failed request during "+ action + ", check url or body: " + str(response.status_code)) 
2023-01-06 14:17:14.859 Error: Volets roulants: exceptions.TahomaException: failed request during send command, check url or body: 400 
2023-01-06 14:17:36.518 Status: User: Admin (IP: 192.168.90.15) initiated a switch command (838/Salon 1/Set Level) 
2023-01-06 14:17:37.425 Error: Volets roulants: Call to function 'onCommand' failed, exception details: 
2023-01-06 14:17:37.425 Error: Volets roulants: Traceback (most recent call last): 
2023-01-06 14:17:37.425 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 582, in onCommand 
2023-01-06 14:17:37.425 Error: Volets roulants: _plugin.onCommand(DeviceId, Unit, Command, Level, Color) 
2023-01-06 14:17:37.425 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 267, in onCommand 
2023-01-06 14:17:37.425 Error: Volets roulants: self.tahoma.send_command(self.command_data) 
2023-01-06 14:17:37.425 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 226, in send_command 
2023-01-06 14:17:37.425 Error: Volets roulants: self.handle_response(response, "send command") 
2023-01-06 14:17:37.425 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 239, in handle_response 
2023-01-06 14:17:37.425 Error: Volets roulants: raise exceptions.TahomaException("failed request during "+ action + ", check url or body: " + str(response.status_code)) 
2023-01-06 14:17:37.425 Error: Volets roulants: exceptions.TahomaException: failed request during send command, check url or body: 400 
2023-01-06 14:18:13.967 Status: Volets roulants: Updating device:Salon 2 
2023-01-06 14:18:13.989 Status: Volets roulants: Updating device:Cuisine 


Plugin logs
[somfy.log](https://github.com/MadPatrick/somfy/files/10360409/somfy.log)

**Comment by jcbraem** [comment]
After an clearing log for debug and restart plugin : severals commands I have error "
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: exceptions.TahomaException: failed request during send command, check url or body: 400".
Have you all informations for you check ?

[somfy.log](https://github.com/MadPatrick/somfy/files/10362253/somfy.log)


`2023-01-06 19:21:01.555 Connexoon Somfy Vélux: Worker thread started.
2023-01-06 19:21:01.555 Status: Connexoon Somfy Vélux: Started.
2023-01-06 19:21:01.555 Status: Connexoon Somfy Vélux: Entering work loop.
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Debug logging mask set to: PYTHON
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameters count: 25
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'HardwareID':'58'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'HomeFolder':'/home/jcb/domoticz/plugins/somfy/'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'StartupFolder':'/home/jcb/domoticz/'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'UserDataFolder':'/home/jcb/domoticz/'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Database':'/home/jcb/domoticz/domoticz.db'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Language':'fr'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Version':'4.2.7'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Author':'MadPatrick'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Name':'Connexoon Somfy Vélux'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Port':'8443'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Username':'j*****@*****.***'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Password':'********'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Key':'tahomaIO'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Mode1':'False'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Mode2':'300'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Mode4':'Web'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'Mode6':'Debug'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'DomoticzVersion':'2022.2'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'DomoticzHash':'eea9db734'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Parameter: 'DomoticzBuildTime':'2022-11-05 13:05:35'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Configuration count: 4
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Configuration 'MajorVersion':'4'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Configuration 'MinorVersion':'2'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Configuration 'patchVersion':'7'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Configuration 'plugin version':'4.2.7'
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Device count: 6
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Device: internal://0828-8553-9093/pod/0 - DeviceID: 'internal://0828-8553-9093/pod/0', Units: 1
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Device: io://0828-8553-9093/13219150 - DeviceID: 'io://0828-8553-9093/13219150', Units: 1
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Device: io://0828-8553-9093/15363054 - DeviceID: 'io://0828-8553-9093/15363054', Units: 1
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Device: io://0828-8553-9093/6070825 - DeviceID: 'io://0828-8553-9093/6070825', Units: 1
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Device: io://0828-8553-9093/7444963 - DeviceID: 'io://0828-8553-9093/7444963', Units: 1
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: Device: io://0828-8553-9093/8877583 - DeviceID: 'io://0828-8553-9093/8877583', Units: 1
2023-01-06 19:21:02.121 Connexoon Somfy Vélux: os.path.exists(Parameters['Mode5']) = False
2023-01-06 19:21:02.122 Connexoon Somfy Vélux: Starting version: 4.2.7
2023-01-06 19:21:02.118 Status: Connexoon Somfy Vélux: Initialized version 4.2.7, author 'MadPatrick'
2023-01-06 19:21:02.121 Status: Connexoon Somfy Vélux: Location does not exist, logging to default location
2023-01-06 19:21:02.121 Status: Connexoon Somfy Vélux: Starting Tahoma blind plugin, logging to file somfy.log
2023-01-06 19:21:59.246 Status: User: Admin (IP: 192.168.2.91) initiated a switch command (544/Store terrasse/Set Level)
2023-01-06 19:22:04.956 Error: Connexoon Somfy Vélux: Call to function 'onCommand' failed, exception details:
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: Traceback (most recent call last):
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 582, in onCommand
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: _plugin.onCommand(DeviceId, Unit, Command, Level, Color)
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 268, in onCommand
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: event_list = self.tahoma.get_events()
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 132, in get_events
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: raise exceptions.TahomaException("No listenerId has been provided")
2023-01-06 19:22:04.960 Error: Connexoon Somfy Vélux: exceptions.TahomaException: No listenerId has been provided
2023-01-06 19:22:05.787 Status: User: Admin (IP: 192.168.2.91) initiated a switch command (542/Store rivière/Close)
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: Call to function 'onCommand' failed, exception details:
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: Traceback (most recent call last):
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 582, in onCommand
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: _plugin.onCommand(DeviceId, Unit, Command, Level, Color)
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 268, in onCommand
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: event_list = self.tahoma.get_events()
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 132, in get_events
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: raise exceptions.TahomaException("No listenerId has been provided")
2023-01-06 19:22:12.135 Error: Connexoon Somfy Vélux: exceptions.TahomaException: No listenerId has been provided
2023-01-06 19:22:18.524 Status: User: Admin (IP: 192.168.2.91) initiated a switch command (541/Vélux palier/Stop)
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: Call to function 'onCommand' failed, exception details:
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: Traceback (most recent call last):
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 582, in onCommand
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: _plugin.onCommand(DeviceId, Unit, Command, Level, Color)
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 268, in onCommand
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: event_list = self.tahoma.get_events()
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 132, in get_events
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: raise exceptions.TahomaException("No listenerId has been provided")
2023-01-06 19:22:22.581 Error: Connexoon Somfy Vélux: exceptions.TahomaException: No listenerId has been provided
2023-01-06 19:22:26.392 Status: User: Admin (IP: 192.168.2.91) initiated a switch command (542/Store rivière/Open)
2023-01-06 19:22:30.238 Error: Connexoon Somfy Vélux: Call to function 'onCommand' failed, exception details:
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: Traceback (most recent call last):
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 582, in onCommand
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: _plugin.onCommand(DeviceId, Unit, Command, Level, Color)
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 267, in onCommand
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: self.tahoma.send_command(self.command_data)
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 226, in send_command
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: self.handle_response(response, "send command")
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 239, in handle_response
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: raise exceptions.TahomaException("failed request during "+ action + ", check url or body: " + str(response.status_code))
2023-01-06 19:22:30.239 Error: Connexoon Somfy Vélux: exceptions.TahomaException: failed request during send command, check url or body: 400
2023-01-06 19:22:31.809 Status: User: Admin (IP: 192.168.2.91) initiated a switch command (542/Store rivière/Open)
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: Call to function 'onCommand' failed, exception details:
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: Traceback (most recent call last):
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 582, in onCommand
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: _plugin.onCommand(DeviceId, Unit, Command, Level, Color)
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 267, in onCommand
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: self.tahoma.send_command(self.command_data)
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 226, in send_command
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: self.handle_response(response, "send command")
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 239, in handle_response
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: raise exceptions.TahomaException("failed request during "+ action + ", check url or body: " + str(response.status_code))
2023-01-06 19:22:44.346 Error: Connexoon Somfy Vélux: exceptions.TahomaException: failed request during send command, check url or body: 400`

**Comment by jcbraem** [comment]
I confirm also, after an restart of plugin it is OK for the same commands !

[somfy.log](https://github.com/MadPatrick/somfy/files/10362312/somfy.log)


`2023-01-06 19:35:58.136 Status: Connexoon Somfy Vélux: Stop directive received.
2023-01-06 19:35:58.155 Status: Connexoon Somfy Vélux: Exiting work loop.
2023-01-06 19:35:58.236 Status: Connexoon Somfy Vélux: Stopping threads.
2023-01-06 19:35:58.236 Status: Connexoon Somfy Vélux: Stopped.
2023-01-06 19:36:06.601 Connexoon Somfy Vélux: Worker thread started.
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Debug logging mask set to: PYTHON
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameters count: 25
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'HardwareID':'58'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'HomeFolder':'/home/jcb/domoticz/plugins/somfy/'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'StartupFolder':'/home/jcb/domoticz/'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'UserDataFolder':'/home/jcb/domoticz/'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Database':'/home/jcb/domoticz/domoticz.db'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Language':'fr'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Version':'4.2.7'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Author':'MadPatrick'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Name':'Connexoon Somfy Vélux'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Port':'8443'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Username':'j*****@*****.***'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Password':'****'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Key':'tahomaIO'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Mode1':'False'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Mode2':'300'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Mode4':'Web'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'Mode6':'Debug'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'DomoticzVersion':'2022.2'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'DomoticzHash':'eea9db734'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Parameter: 'DomoticzBuildTime':'2022-11-05 13:05:35'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Configuration count: 4
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Configuration 'MajorVersion':'4'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Configuration 'MinorVersion':'2'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Configuration 'patchVersion':'7'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Configuration 'plugin version':'4.2.7'
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Device count: 6
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Device: internal://0828-8553-9093/pod/0 - DeviceID: 'internal://0828-8553-9093/pod/0', Units: 1
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Device: io://0828-8553-9093/13219150 - DeviceID: 'io://0828-8553-9093/13219150', Units: 1
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Device: io://0828-8553-9093/15363054 - DeviceID: 'io://0828-8553-9093/15363054', Units: 1
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Device: io://0828-8553-9093/6070825 - DeviceID: 'io://0828-8553-9093/6070825', Units: 1
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Device: io://0828-8553-9093/7444963 - DeviceID: 'io://0828-8553-9093/7444963', Units: 1
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: Device: io://0828-8553-9093/8877583 - DeviceID: 'io://0828-8553-9093/8877583', Units: 1
2023-01-06 19:36:06.798 Connexoon Somfy Vélux: os.path.exists(Parameters['Mode5']) = False
2023-01-06 19:36:06.799 Connexoon Somfy Vélux: Starting version: 4.2.7
2023-01-06 19:36:06.601 Status: Connexoon Somfy Vélux: Started.
2023-01-06 19:36:06.601 Status: Connexoon Somfy Vélux: Entering work loop.
2023-01-06 19:36:06.795 Status: Connexoon Somfy Vélux: Initialized version 4.2.7, author 'MadPatrick'
2023-01-06 19:36:06.798 Status: Connexoon Somfy Vélux: Location does not exist, logging to default location
2023-01-06 19:36:06.798 Status: Connexoon Somfy Vélux: Starting Tahoma blind plugin, logging to file somfy.log
2023-01-06 19:36:41.650 Status: User: Admin (IP: 192.168.2.91) initiated a switch command (544/Store terrasse/Open)
2023-01-06 19:36:44.656 Status: User: Admin (IP: 192.168.2.91) initiated a switch command (542/Store rivière/Open)
2023-01-06 19:36:45.030 Status: Connexoon Somfy Vélux: Updating device:Store terrasse`

**Comment by JanJaapKo** [comment]
@Abidos14 can you explain why or how you get those multiple commands at a time? The easy solution would be to filter the list of commands and just make sure there is only one per device (hopefully I can take the last one)?

**Comment by JanJaapKo** [comment]
OK, I already see where it went wrong: there is a failure on getting events and it remembers failed commands. But the get events is not a failed command. Anyhow, just pushed a solution, can you check?

**Comment by ab10002** [comment]
I'v now every minute odd sensors updates

**Comment by jcbraem** [comment]
Hello,
After several tests with new version 4.2.9 the issue is, I think, now solved !
I confirm after a couple of day and all automatic command from Lua Script.

I have also seen an quickly update of device in widget ... but at this time, no error !
One minute is 'my dream' ...

Thanks for your update !

**Comment by JanJaapKo** [comment]
@jcbraem good news!
@ab10002 please create a separate issue if the irregular updates remain. With logging and description.

**Comment by Abidos14** [comment]
Hello,
Indeed, the error disappeared. Everything seems to be OK now on my side.
@Jan-Jaap : Thank you very much for your work !!

    Le lundi 9 janvier 2023 à 21:35:22 UTC+1, Jan-Jaap Kostelijk ***@***.***> a écrit :  
 
 


Closed #40 as completed.
