### ISSUE TITLE
Not working since update

### ISSUE THREAD

**Issue by Doudou14** [MadPatrick/somfy#45]
Hi,

There was an update yesterday on the Tahoma and since then the script not working
Has somfy changed something where or the problem comes from me?
I have these errors in the logs.
Thank

**log**
2023-01-19 16:09:43.368 Error: Tahoma: Call to function 'onHeartbeat' failed, exception details:
2023-01-19 16:09:43.373 Error: Tahoma: Traceback (most recent call last):
2023-01-19 16:09:43.374 Error: Tahoma: File "/home/Snake/domoticz/plugins/somfy/plugin.py", line 611, in onHeartbeat
2023-01-19 16:09:43.374 Error: Tahoma: _plugin.onHeartbeat()
2023-01-19 16:09:43.374 Error: Tahoma: File "/home/Snake/domoticz/plugins/somfy/plugin.py", line 307, in onHeartbeat
2023-01-19 16:09:43.374 Error: Tahoma: filtered_devices = self.tahoma.get_devices()
2023-01-19 16:09:43.374 Error: Tahoma: File "/home/Snake/domoticz/plugins/somfy/tahoma_local.py", line 188, in get_devices
2023-01-19 16:09:43.374 Error: Tahoma: utils.handle_response(response, "get devices")
2023-01-19 16:09:43.375 Error: Tahoma: File "/home/Snake/domoticz/plugins/somfy/utils.py", line 84, in handle_response
2023-01-19 16:09:43.375 Error: Tahoma: raise exceptions.TahomaException("failed request during "+ action + ", check credentials: " + str(response.status_code))
2023-01-19 16:09:43.375 Error: Tahoma: exceptions.TahomaException: failed request during get devices, check credentials: 401

EDIT : The script is up to date

**Comment by JanJaapKo** [comment]
Hey,

I need the somfy.log file to check whatvis going wrong

**Comment by Doudou14** [comment]
The log file is more than 2GB I don't understand why. I can't open it. I installed the script 2 weeks ago
I deleted it the new file gives this : 
2023-01-19 19:15:05,758 - INFO     - plugin.py          - starting plugin version 4.2.14
2023-01-19 19:15:05,764 - INFO     - plugin.py          - Starting version: 4.2.14
2023-01-19 19:15:06,545 - INFO     - tahoma_local.py    - Tahoma authentication succeeded, login valid until 2023-01-25 19:15:06
2023-01-19 19:15:07,214 - ERROR    - utils.py           - status code 401 authorisation failed, check credentials
2023-01-19 19:16:06,400 - ERROR    - utils.py           - status code 401 authorisation failed, check credentials

**Comment by JanJaapKo** [comment]
duplicates #46
