### ISSUE TITLE
Somfy Tahoma/Connexoon plugin  version: 4.2.16 error

### ISSUE THREAD

**Issue by eekhoorn** [MadPatrick/somfy#58]
Plugin not working using domoticz 2024.4:
This error in the log:
`2024-06-19 03:17:31.201 Error: Somfy: Failed to request data: HTTPSConnectionPool(host='xxxxxxxxx.local', port=8443): Max retries exceeded with url: /enduser-mobile-web/1/enduserAPI/setup/devices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5dcf8058>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-19 03:17:51.039 Error: Somfy: Call to function 'onHeartbeat' failed, exception details:
2024-06-19 03:17:51.054 Error: Somfy: Traceback (most recent call last):
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 612, in onHeartbeat
2024-06-19 03:17:51.054 Error: Somfy: _plugin.onHeartbeat()
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 308, in onHeartbeat
2024-06-19 03:17:51.054 Error: Somfy: filtered_devices = self.tahoma.get_devices()
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/tahoma_local.py", line 189, in get_devices
2024-06-19 03:17:51.054 Error: Somfy: filtered_list = utils.filter_devices(response.json())
2024-06-19 03:17:51.054 Error: Somfy: File "/home/pi/domoticz/plugins/somfy/utils.py", line 17, in filter_devices
2024-06-19 03:17:51.054 Error: Somfy: logging.debug("filter_devices: Device name: "+device["label"]+" Device class: "+device["definition"]["uiClass"])
2024-06-19 03:17:51.054 Error: Somfy: KeyError: 'definition'`

**Comment by MadPatrick** [comment]
Do you have this on in domoticz 2024.4 or also in previous version?
Is this error just appearing  once on contantly ?  If it is once and the devices are operating it is just a connection failure at Somfy
They popup once and a while.
